function ColorVim()
    -- vim.cmd("colorscheme catppuccin-frappe")
    -- vim.cmd('colorscheme doom-one')
    vim.cmd("colorscheme kanagawa-wave")
    -- vim.cmd("colorscheme kanagawa-dragon")
    -- vim.cmd("colorscheme kanagawa-lotus")
    -- vim.cmd("colorscheme fahrenheit")
	-- vim.api.nvim_set_hl(0, "Normal", { bg = "white" })
	-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "white" })
end
ColorVim()
